name: CI - .NET Testes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências
      run: dotnet restore

    - name: Compilar o projeto
      run: dotnet build --configuration Debug

    - name: Instalar ferramenta CLI do Playwright
      run: dotnet tool install --global Microsoft.Playwright.CLI

    - name: Adicionar ferramenta global ao PATH
      run: echo "${{ runner.tool_cache }}/dotnet/tools" >> $GITHUB_PATH

    - name: Instalar navegadores do Playwright
      run: playwright install

    - name: Rodar testes
      run: dotnet test --logger:"trx;LogFileName=resultado.trx"

    - name: Publicar artefato de resultados TRX
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: '**/TestResults/*.trx'
