name: CI Testes com Relatório HTML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar o projeto
        run: dotnet build --configuration Debug

      - name: Instalar navegadores do Playwright
        run: pwsh "$(Get-ChildItem -Path ./bin/Debug/net*/playwright.ps1 -Recurse | Select-Object -First 1).FullName" install

      - name: Rodar testes e gerar TRX
        run: dotnet test --logger "trx;LogFileName=resultado.trx" --results-directory TestResults

      - name: Baixar trx2html.exe
        run: curl -LJO https://github.com/gmarchetti/trx2html/releases/download/v0.9.0/trx2html.exe

      - name: Gerar relatório HTML do TRX
        run: ./trx2html.exe TestResults/resultado.trx TestResults/relatorio.html

      - name: Upload do relatório HTML
        uses: actions/upload-artifact@v4
        with:
          name: Testes-Relatorio-HTML
          path: TestResults/relatorio.html
