name: CI .NET testes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar o projeto
        run: dotnet build --configuration Debug

      - name: Instalar navegadores do Playwright
        run: pwsh -Command "& './bin/Debug/net8.0/playwright.ps1' install"

      - name: Rodar testes com logger TRX
        run: dotnet test --no-build --configuration Debug --logger "trx;LogFileName=resultado.trx" --results-directory TestResults

      - name: Baixar trx2html
        run: curl -LJO https://github.com/gmarchetti/trx2html/releases/download/v0.9.0/trx2html.exe

      - name: Gerar relatório HTML do TRX
        run: ./trx2html.exe TestResults/resultado.trx TestResults/relatorio.html

      - name: Upload do relatório de testes
        uses: actions/upload-artifact@v4
        with:
          name: Relatorio-Testes-Executados
          path: TestResults/relatorio.html
