name: CI - .NET Testes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências
      run: dotnet restore

    - name: Rodar testes
      run: dotnet test --logger:"trx;LogFileName=resultado.trx"
