name: CI HTML relatorio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar o projeto
        run: dotnet build --configuration Debug

      - name: Instalar Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Adicionar Playwright CLI ao PATH
        run: echo "${{ runner.tool_cache }}/dotnet/tools" >> $GITHUB_PATH

      - name: Instalar navegadores do Playwright
        run: playwright install

      - name: Rodar testes e gerar arquivo TRX
        run: dotnet test --logger "trx;LogFileName=resultado.trx" --results-directory "TestResults"

      - name: Instalar ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Gerar relatório HTML dos testes
        run: reportgenerator -reports:TestResults/resultado.trx -targetdir:TestResults/html -reporttypes:Html

      - name: Upload do relatório HTML
        uses: actions/upload-artifact@v4
        with:
          name: Relatorio-Testes-HTML
          path: TestResults/html/index.htm
